export const CATEGORY_LOAD = "CATEGORY_LOAD"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_ERROR = "CATEGORY_ERROR"
export const CATEGORY_CREAT = "CATEGORY_CREAT"
export const CATEGORY_DELETE = "CATEGORY_DELETE"

